16 create route with spotify data statistics
Rigtch/rigtch-music-api pull request #21
Opened 2022-11-05 11:41 UTC by Mnigos

closes #16

2022-11-05 14:04 UTC, Mnigos commented
fix jwt guard from libs

2022-11-05 14:04 UTC, Mnigos commented
create unit tests for statistics service and resolver

2022-11-05 14:50 UTC, Mnigos commented
fix jest error with enums

2022-11-07 16:23 UTC, Iqro-dev requested changes

2022-11-07 16:23 UTC, Iqro-dev commented on apps/statistics/src/utils/format-tracks.spec.ts
> +describe('format-tracks', () => {
you use two different types of describing those tests, here u use 'name-name' but in others 'NameName'

2022-11-07 16:23 UTC, Iqro-dev commented on apps/statistics/src/statistics.service.spec.ts
> +describe('StatisticsService', () => {
same issue here

2022-11-07 16:27 UTC, Mnigos commented on libs/utils/src/catch-spotify-error.spec.ts
> +describe('catchSpotifyError', () => {
this is because function name is camelCased but class name like `StatisticsController` is PascalCased

2022-11-07 17:16 UTC, Iqro-dev approved these changes

2022-11-07 17:47 UTC, merged